theme: minima
title: My200BirdYear
author: Adam Skinner
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  A selection of the photos taken for the Bird Watching Magazines #My200BirdYear.

# social links
twitter_username: adamjskinnerphotography
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
